create table if not exists public.leaderboard_entries (
  id bigint generated by default as identity primary key,
  initials text not null,
  score integer not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  constraint leaderboard_entries_initials_format
    check (initials ~ '^[A-Z]{3}$'),
  constraint leaderboard_entries_score_nonnegative
    check (score >= 0)
);

create index if not exists leaderboard_entries_rank_idx
  on public.leaderboard_entries (score desc, created_at asc);

alter table public.leaderboard_entries enable row level security;

grant select, insert on public.leaderboard_entries to anon, authenticated;
grant usage, select on sequence public.leaderboard_entries_id_seq to anon, authenticated;

drop policy if exists "Public leaderboard read" on public.leaderboard_entries;
create policy "Public leaderboard read"
  on public.leaderboard_entries
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public leaderboard submit" on public.leaderboard_entries;
create policy "Public leaderboard submit"
  on public.leaderboard_entries
  for insert
  to anon, authenticated
  with check (true);
